Update ci-python.yml

diff --git a/.github/workflows/ci-python.yml b/.github/workflows/ci-python.yml
--- a/.github/workflows/ci-python.yml
+++ b/.github/workflows/ci-python.yml
@@ -5,13 +5,13 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-    name: Build
-    uses: ./.github/workflows/bazel.yml
-    with:
-      name: Build
-      cache-key: py-build
-      run: bazel build //py:selenium-wheel //py:selenium-sdist
+  # build:
+  #   name: Build
+  #   uses: ./.github/workflows/bazel.yml
+  #   with:
+  #     name: Build
+  #     cache-key: py-build
+  #     run: bazel build //py:selenium-wheel //py:selenium-sdist
 
   docs:
     name: Documentation
@@ -20,7 +20,6 @@ jobs:
     steps:
       - name: Debugging with tmate
         uses: mxschmitt/action-tmate@v3.14
-
       - name: Checkout source tree
         uses: actions/checkout@v3
       - name: Set up Python 3.7
@@ -41,6 +40,8 @@ jobs:
     needs: build
     runs-on: ubuntu-20.04
     steps:
+      - name: Debugging with tmate
+        uses: mxschmitt/action-tmate@v3.14
       - name: Checkout source tree
         uses: actions/checkout@v3
       - name: Set up Python 3.7
@@ -56,59 +57,59 @@ jobs:
         env:
           TOXENV: linting-check
 
-  mypy:
-    name: Mypy
-    needs: build
-    runs-on: ubuntu-20.04
-    steps:
-      - name: Checkout source tree
-        uses: actions/checkout@v3
-      - name: Set up Python 3.7
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.7.10
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install tox==2.4.1
-      - name: Test with tox
-        run: |
-          tox -c py/tox.ini -- --cobertura-xml-report ci || true
-          bash <(curl -s https://codecov.io/bash) -f py/ci/cobertura.xml
-        env:
-          TOXENV: mypy
+  # mypy:
+  #   name: Mypy
+  #   needs: build
+  #   runs-on: ubuntu-20.04
+  #   steps:
+  #     - name: Checkout source tree
+  #       uses: actions/checkout@v3
+  #     - name: Set up Python 3.7
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: 3.7.10
+  #     - name: Install dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         pip install tox==2.4.1
+  #     - name: Test with tox
+  #       run: |
+  #         tox -c py/tox.ini -- --cobertura-xml-report ci || true
+  #         bash <(curl -s https://codecov.io/bash) -f py/ci/cobertura.xml
+  #       env:
+  #         TOXENV: mypy
 
-  unit-tests:
-    name: Unit Tests
-    needs: build
-    uses: ./.github/workflows/bazel.yml
-    with:
-      name: Unit Tests
-      cache-key: py-unit
-      run: bazel test //py:unit
+  # unit-tests:
+  #   name: Unit Tests
+  #   needs: build
+  #   uses: ./.github/workflows/bazel.yml
+  #   with:
+  #     name: Unit Tests
+  #     cache-key: py-unit
+  #     run: bazel test //py:unit
 
-  browser-tests:
-    name: Browser Tests
-    needs: unit-tests
-    uses: ./.github/workflows/bazel.yml
-    strategy:
-      fail-fast: false
-      matrix:
-        browser:
-          - chrome
-          - firefox
-    with:
-      name: Integration Tests (${{ matrix.browser }})
-      browser: ${{ matrix.browser }}
-      cache-key: py-${{ matrix.browser }}
-      run: bazel test --flaky_test_attempts 3 //py:test-${{ matrix.browser }}
+  # browser-tests:
+  #   name: Browser Tests
+  #   needs: unit-tests
+  #   uses: ./.github/workflows/bazel.yml
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       browser:
+  #         - chrome
+  #         - firefox
+  #   with:
+  #     name: Integration Tests (${{ matrix.browser }})
+  #     browser: ${{ matrix.browser }}
+  #     cache-key: py-${{ matrix.browser }}
+  #     run: bazel test --flaky_test_attempts 3 //py:test-${{ matrix.browser }}
 
-  remote-tests:
-    name: Remote Tests
-    needs: unit-tests
-    uses: ./.github/workflows/bazel.yml
-    with:
-      name: Integration Tests (remote)
-      browser: firefox
-      cache-key: py-remote
-      run: bazel test --local_test_jobs 1 --flaky_test_attempts 3 //py:test-remote
+  # remote-tests:
+  #   name: Remote Tests
+  #   needs: unit-tests
+  #   uses: ./.github/workflows/bazel.yml
+  #   with:
+  #     name: Integration Tests (remote)
+  #     browser: firefox
+  #     cache-key: py-remote
+  #     run: bazel test --local_test_jobs 1 --flaky_test_attempts 3 //py:test-remote
